services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

  sentiment-api:
    build: .
    container_name: sentiment-api
    ports:
      - "7860:7860"
    environment:
      - HF_HOME=/hf
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - /home/ahtuh-in/.cache/huggingface:/hf:ro
    command: ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "7860"]
    depends_on:
      - chroma

  sentiment-ui:
    build: .
    container_name: sentiment-ui
    ports:
      - "7861:7860"
    environment:
      - HF_HOME=/hf
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - /home/ahtuh-in/.cache/huggingface:/hf:ro
    command: ["python", "-m", "app.ui"]
    depends_on:
      - sentiment-api

volumes:
  chroma_data:
